"""rename department

Revision ID: 56596bdf4660
Revises: 89c78e186288
Create Date: 2023-11-13 10:11:15.214101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56596bdf4660'
down_revision = '89c78e186288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
