"""rename address

Revision ID: aea34527228d
Revises: 56596bdf4660
Create Date: 2023-11-13 10:15:02.248893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea34527228d'
down_revision = '56596bdf4660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name=('location'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name=('address'))
    # ### end Alembic commands ###
